DROP TABLE IF EXISTS "DEMO";
CREATE TABLE IF NOT EXISTS "DEMO"
(
    "ID" INT IDENTITY(1, 1) NOT NULL,
    "CR_TIME" TIMESTAMP(0),
    "CR_USER" VARCHAR(255),
    NOT CLUSTER PRIMARY KEY("ID")
);

COMMENT ON COLUMN "DEMO"."CR_TIME" IS '创建时间';
COMMENT ON COLUMN "DEMO"."CR_USER" IS '创建人';

-- SELECT * FROM DBA_TAB_COLUMNS
-- 上面这个需要数据库用户具有 DBA 角色
CREATE OR REPLACE PROCEDURE add_column
AS
BEGIN
IF NOT EXISTS(SELECT * FROM DBA_TAB_COLUMNS WHERE OWNER= SF_GET_SCHEMA_NAME_BY_ID(CURRENT_SCHID()) AND TABLE_NAME='DEMO' AND COLUMN_NAME='DEMO_DATA')
THEN
EXECUTE IMMEDIATE 'ALTER TABLE "DEMO" ADD COLUMN("DEMO_DATA" NUMBER(20,2))';
EXECUTE IMMEDIATE 'COMMENT ON COLUMN "DEMO"."DEMO_DATA" IS ''测试数据''';
END IF;
END;
/
CALL add_column();
/
DROP PROCEDURE IF EXISTS "add_column";
