DROP TABLE IF EXISTS DEMO;

CREATE TABLE DEMO (
    ID VARCHAR2(36) NOT NULL,
    CR_TIME TIMESTAMP(6),
    CR_USER VARCHAR(255),
    PRIMARY KEY(ID)
);

COMMENT ON COLUMN DEMO.CR_TIME IS '创建时间';
COMMENT ON COLUMN DEMO.CR_USER IS '创建人';
